################################################################################
# 自动生成的文件。不要编辑！
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fdcan.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fmac.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_hrtim.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp_ex.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi_ex.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c \
D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c 

OBJS += \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_fdcan.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_fmac.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_hrtim.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_spi.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_spi_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_adc.o 

C_DEPS += \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_fdcan.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_fmac.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_hrtim.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_spi.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_spi_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_adc.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc_ex.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_fdcan.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fdcan.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_fmac.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fmac.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_hrtim.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_hrtim.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp_ex.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp_ex.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_spi.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_spi_ex.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_spi_ex.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_adc.o: D:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O0 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -DUSE_HAL_DRIVER -DSTM32G474xx -D__CC_ARM -D__FPU_PRESENT = 1U -DARM_MATH_CM4 -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Core/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Device/ST/STM32G4xx/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/Include -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP -ID:/RT-ThreadStudio/workspace/Ultra_CAP/Drivers/CMSIS/DSP/Include -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

